/* Pure scheduling and phrase-selection functions; no dependencies. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.IstanteCore=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DAY=86400000;
const DEFAULTS=Object.freeze({mode:'twice',morning:'06:00',evening:'18:00',interval:30,theme:'dark',background:'ambient',showClock:true,showSeconds:false,motion:true,hideControls:true,wakeLock:false,goalMode:'year',goalTitle:'',goalStart:'',goalEnd:'',photoDim:65});
function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function random(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function shuffle(items,rng){const a=items.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function normalized(text){return text.toLocaleLowerCase('it').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();}
function themeKey(text){let s=normalized(text).replace(/[.!?]+$/,'');const prefixes=['ricorda:','non dimenticare:','tieni a mente:','oggi ricorda:','abbi fiducia:','continua a credere:','concediti di pensare:','lascia spazio alla possibilita che ','non avere paura di scoprire che ','puoi sempre ricordare che '];const prefix=prefixes.find(p=>s.startsWith(p));if(prefix)return s.slice(prefix.length).trim();const suffixes=[' senza confrontarti con nessuno',' senza cercare approvazione',' anche quando e difficile',' un giorno alla volta',' anche se hai paura',' per te stesso',' senza fretta',' con calma',' ancora',' oggi'];const suffix=suffixes.find(p=>s.endsWith(p));if(suffix)s=s.slice(0,-suffix.length);return s;}
function parsePhrases(payload){const source=Array.isArray(payload)?payload:payload&&payload.phrases;if(!Array.isArray(source)||source.length<1||source.length>10000)throw new Error('Il JSON deve contenere un elenco "phrases" da 1 a 10.000 testi.');const seen=new Set(),phrases=[];source.forEach((item,index)=>{if(typeof item!=='string'||!item.trim()||item.length>1000)throw new Error('La frase '+(index+1)+' non \u00e8 valida: serve un testo da 1 a 1.000 caratteri.');if(!seen.has(item)){seen.add(item);phrases.push({id:'q-'+hash(item).toString(36)+'-'+index,text:item,group:themeKey(item),search:normalized(item),sourceIndex:index});}});return phrases;}
function buildDeck(phrases){const signature=hash(phrases.map(p=>p.text).join('\n')),rng=random(signature),groups=new Map();phrases.forEach(p=>{if(!groups.has(p.group))groups.set(p.group,[]);groups.get(p.group).push(p);});const buckets=shuffle([...groups.values()],rng).map(a=>shuffle(a,rng)),result=[];let round=0;while(result.length<phrases.length){for(const bucket of buckets)if(bucket[round])result.push(bucket[round]);round++;}return{items:result,signature:signature.toString(36),groups:groups.size};}
function minutes(value,fallback){if(typeof value!=='string'||!/^\d{2}:\d{2}$/.test(value))return fallback;const[h,m]=value.split(':').map(Number);return h<=23&&m<=59?h*60+m:fallback;}
function cleanSettings(input){const x=Object.assign({},DEFAULTS);if(!input||typeof input!=='object')return x;const choices={mode:['twice','daily','interval','opening'],theme:['dark','light','auto'],background:['ambient','plain','photo'],goalMode:['year','custom','off']};for(const[key,values]of Object.entries(choices))if(values.includes(input[key]))x[key]=input[key];for(const key of ['showClock','showSeconds','motion','hideControls','wakeLock'])if(typeof input[key]==='boolean')x[key]=input[key];if([5,15,30,60].includes(Number(input.interval)))x.interval=Number(input.interval);const morning=minutes(input.morning,360),evening=minutes(input.evening,1080);if(x.mode!=='twice'||morning<evening){x.morning=String(Math.floor(morning/60)).padStart(2,'0')+':'+String(morning%60).padStart(2,'0');x.evening=String(Math.floor(evening/60)).padStart(2,'0')+':'+String(evening%60).padStart(2,'0');}for(const key of ['goalStart','goalEnd'])if(typeof input[key]==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(input[key])&&Number.isFinite(new Date(input[key]).getTime()))x[key]=input[key];if(typeof input.goalTitle==='string')x.goalTitle=input.goalTitle.trim().slice(0,90);if(Number.isFinite(Number(input.photoDim)))x.photoDim=Math.max(35,Math.min(85,Number(input.photoDim)));if(x.goalMode==='custom'&&(!x.goalStart||!x.goalEnd||new Date(x.goalEnd)<=new Date(x.goalStart)))x.goalMode='year';return x;}
function localDay(date){return Math.floor(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())/DAY);}
function atMinutes(date,minute,delta){return new Date(date.getFullYear(),date.getMonth(),date.getDate()+(delta||0),Math.floor(minute/60),minute%60,0,0);}
function getSchedule(date,settings){const start=minutes(settings.morning,360),end=minutes(settings.evening,1080),minute=date.getHours()*60+date.getMinutes(),day=localDay(date)-(minute<start?1:0);if(settings.mode==='opening')return{key:'opening',ordinal:null,label:'Un pensiero per te',nextAt:null,part:'opening'};if(settings.mode==='interval'){const duration=settings.interval*60000,ordinal=Math.floor(date.getTime()/duration);return{key:'interval:'+settings.interval+':'+ordinal,ordinal,label:'Un pensiero, adesso',nextAt:new Date((ordinal+1)*duration),part:'interval'};}if(settings.mode==='daily')return{key:'daily:'+start+':'+day,ordinal:day,label:'Il pensiero del giorno',nextAt:atMinutes(date,start,minute<start?0:1),part:'daily'};const isMorning=minute>=start&&minute<end,ordinal=day*2+(isMorning?0:1);return{key:'twice:'+start+':'+end+':'+ordinal,ordinal,label:isMorning?'Il pensiero del mattino':'Il pensiero della sera',nextAt:isMorning?atMinutes(date,end):atMinutes(date,start,minute<start?0:1),part:isMorning?'morning':'evening'};}
function pickScheduled(deck,ordinal){return deck[((ordinal%deck.length)+deck.length)%deck.length];}
function getGoal(date,settings){if(settings.goalMode==='off')return null;const year=date.getFullYear(),start=settings.goalMode==='custom'?new Date(settings.goalStart):new Date(year,0,1),end=settings.goalMode==='custom'?new Date(settings.goalEnd):new Date(year+1,0,1),ms=Math.max(0,end.getTime()-date.getTime()),progress=Math.min(100,Math.max(0,(date-start)/(end-start)*100));return{title:settings.goalMode==='custom'?(settings.goalTitle||'Il mio traguardo'):'Verso il '+(year+1),start,end,progress,done:date>=end,waiting:date<start,days:Math.floor(ms/DAY),hours:Math.floor(ms/3600000)%24,minutes:Math.floor(ms/60000)%60,seconds:Math.floor(ms/1000)%60};}
function splitPhrase(text){const i=text.indexOf(':');return i>0&&i<32?{intro:text.slice(0,i+1),body:text.slice(i+1).trimStart()}:{intro:'',body:text};}
return{DEFAULTS,hash,normalized,themeKey,parsePhrases,buildDeck,minutes,cleanSettings,localDay,getSchedule,pickScheduled,getGoal,splitPhrase};
});
